In [5]:
a = [10,20,30]

3-element Vector{Int64}:
 10
 20
 30

In [6]:
function allPermute(a)
    function permuteRight(a)
        a2 = copy(a)
        b = zeros(Int64,length(a))
        for i in 1:(length(a)-1)
            b[i+1] = a2[i]
        end
        b[1] = a2[end]
        return b
    end
        global allPerms = []
        for i in 1:(length(a))
            push!(allPerms,permuteRight(a))
            a = permuteRight(a)
        end
        return allPerms
end

allPermute (generic function with 1 method)

In [7]:
allPermute(a)

3-element Vector{Any}:
 [30, 10, 20]
 [20, 30, 10]
 [10, 20, 30]

In [8]:
allPermute([1,5,9,7,5,9])

6-element Vector{Any}:
 [9, 1, 5, 9, 7, 5]
 [5, 9, 1, 5, 9, 7]
 [7, 5, 9, 1, 5, 9]
 [9, 7, 5, 9, 1, 5]
 [5, 9, 7, 5, 9, 1]
 [1, 5, 9, 7, 5, 9]